### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by Milchreis** [Milchreis/QuickNotes#1]
![grafik](https://user-images.githubusercontent.com/544436/69248512-b6f4d300-0bac-11ea-9595-66ac1221fad9.png)

**Changes**
```css
.CodeMirror {
  /* background: #fff; */
  background: #2d2d2d;
}

.CodeMirror {
  /* color: #000; */
  color: #c8c8c8;
}

.CodeMirror {
  /* border: 1px solid #ddd; */
}

.editor-toolbar {
  /* border-top: 1px solid #bbb; */
  /* border-left: 1px solid #bbb; */
  /* border-right: 1px solid #bbb; */
}

.editor-toolbar a {
  /* text-decoration: none !important; */
  /* color: #2c3e50 !important; */
  color: #eeeeee !important;
}

.editor-toolbar a.active, .editor-toolbar a:hover {
  /* background: #fcfcfc; */
  /* border-color: #95a5a6; */
  background: #333;
  border-color: #555;
}

.editor-toolbar {
  /* background-color: #fff; */
  background-color: #171717;
}

::selection {
  /* background-color: #b3d4fc; */
  background-color: #a8a8a8;
}
```
